### ISSUE TITLE
Suddenly lists

### ISSUE THREAD

**Issue by ottonemo** [dnouri/inferno#11]
`get_iterator` blows up at https://github.com/dnouri/inferno/blob/169e1a0/inferno/net.py#L310 in case sklearn CV split is used and a 1-dimensional torch tensor is fed for X and y.

For example:

```
pl = GridSearchCV(trainer, params)
pl.fit(corpus.train, corpus.train)
```

**Comment by benjamin-work** [comment]
I have investigated the reason and it is caused by sklearn's [`safe_indexing`](https://github.com/scikit-learn/scikit-learn/blob/02a31f0a891bdf7edc8fb087e11f74ad7a597b8a/sklearn/utils/__init__.py#L122):

```
import torch
from sklearn.utils import safe_indexing
xx = torch.zeros((10, 3))
safe_indexing(xx, [0, 1])

# returns:
# [
#   0
#   0
#   0
#  [torch.FloatTensor of size 3], 
#   0
#   0
#   0
#  [torch.FloatTensor of size 3]]
```

To sum up, `safe_indexing` is often used to index data in sklearn. But this function only works well with pandas DataFrames (via `iloc`) or numpy arrays (via `shape`). If the array is neither, sklearn defaults to `[X[idx] for idx in indices]`, which works for lists but not for torch arrays.

If we want to solve this without changing sklearn or pytorch (if only pytorch tensors had a `shape` attribute intsead of `size` ...), I would suggest that we require the data to be in the numpy world if the user wants to benefit from sklearn goodies.

**Comment by ottonemo** [comment]
So in essence everywhere we communicate with sklearn we have to make sure that the data is formatted as numpy arrays?

**Comment by benjamin-work** [comment]
That would be the safest solution. We could also patch pytorch arrays to have a `shape` attribute and would be fine ;)

**Comment by benjamin-work** [comment]
*Update*: Now torch tensors have a shape attribute, but it still doesn't work (because of https://github.com/pytorch/pytorch/issues/2305).

```
>>> from sklearn.utils import safe_indexing
>>> import torch
>>> xx = torch.zeros((10, 3))
>>> safe_indexing(xx, [0, 1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bbossan_dev/anaconda3/envs/inferno/lib/python3.6/site-packages/sklearn/utils/__init__.py", line 112, in safe_indexing
    return X[indices]
TypeError: indexing a tensor with an object of type list. The only supported types are integers, slices, numpy scalars and torch.LongTensor or torch.ByteTensor as the only argument.
```

However, this works:

```
>>> safe_indexing(xx, ([0, 1],))
 0  0  0
 0  0  0
[torch.FloatTensor of size 2x3]
```

A workaround could thus be to always wrap list indices in a tuple, since it works for pytorch and doesn't interfere with numpy.

**Comment by ottonemo** [comment]
The issue regarding `GridSearchCV` is solved with this solution. Therefore I'm closing this.
